export const arrayWorkLink = [
  {
    id: 1001,
    link: "./img/home/banner/tomato_juice01.webp",
    alt: "トマトジュースのバナー",
  },
  {
    id: 1002,
    link: "./img/home/banner/tomato_juice02.webp",
    alt: "トマトジュースのバナー",
  },
  {
    id: 1003,
    link: "./img/home/flier/sandwich.webp",
    alt: "サンドイッチのチラシ",
  },
  {
    id: 1004,
    link: "./img/home/banner/skin_serum.webp",
    alt: "美容液のバナー",
  },
  {
    id: 1005,
    link: "./img/home/flier/hair_salon.webp",
    alt: "美容室のチラシ",
  },
  {
    id: 1006,
    link: "./img/home/web/burger_shop_recurrent.webp",
    alt: "ハンバーガー「BURGER-SHOP RECURRENT」のwebサイト",
  },
  {
    id: 1007,
    link: "./img/home/banner/cram_school01.webp",
    alt: "夏期講習のバナー",
  },
  {
    id: 1008,
    link: "./img/home/banner/cram_school02.webp",
    alt: "夏期講習のバナー",
  },
  {
    id: 1009,
    link: "./img/home/flier/hamburger.webp",
    alt: "ハンバーガーのポスター",
  },
  {
    id: 1010,
    link: "./img/home/web/guilty-cotton.webp",
    alt: "アイス「guilty-cotton」のWebサイト",
  },
  {
    id: 1011,
    link: "./img/home/movie/museum.webp",
    alt: "長濱美術館「モカそれからの100年」のショート動画",
  },
];

export const arrayLabel = [
  { number: 1, labelName: "個人制作" },
  { number: 1, labelName: "チーム制作" },
];

export const arryaTag = [
  { value: "bn", tagName: "#banner" },
  { value: "web", tagName: "#web" },
  { value: "vi", tagName: "#video" },
  { value: "fl", tagName: "#flier" },
  { value: "mv", tagName: "#movie" },
  { value: "cd", tagName: "#模写コーディング" },
];

export const arrayWorkDetail = [
  {
    id: 1001,
    title: "トマトジュース「赤の習慣」",
    link: "./img/work/banner/tomato_juice01.webp",
    url: "",
    target: "子供を持つ30〜40代の女性",
    purpose: "トマトジュース「赤の習慣」の販売促進",
    point:
      "子供の写真を使用することで、子供でも飲みやすく、日常的に取り入れやすい飲み物という印象を持たせるように意識した。<br><br>「すっきり」というワードを強調し、爽やかな印象のトマトの写真を使用することで、トマトジュースにありがちな「どろっとして飲みにくい」というイメージを払拭し、すっきりとした飲みやすさを表現した。<br><br>「食塩不使用」「リコピン豊富」などの商品の特徴は、ひと目で内容が伝わるようアイコンを使用して視覚的に整理した。<br>さらに、写真や図形を重ねて配置することで、平面的にならないよう立体感を出し、視線を引きつけるレイアウトにした。",
    time: "6時間",
    size: "1080×1080px",
    tool: "Illustrator / Photoshop",
    value: ["bn"],
    number: 1,
  },
  {
    id: 1002,
    title: "トマトジュース「赤の習慣」",
    link: "./img/work/banner/tomato_juice02.webp",
    url: "",
    target: "栄養不足を気にしている20代女性",
    purpose: "トマトジュース「赤の習慣」の販売促進  ",
    point:
      "商品の特徴である「リコピン豊富」「食塩不使用」などの情報は、ひと目で認識できるよう、文字のジャンプ率をつけてメリハリを出した。<br><br>トマトの写真やイラストを複数使用することで、1缶にたっぷりのトマトが使われているようなイメージを表現し、健康を意識する方に向けて、トマトの栄養を手軽に取り入れられる商品であることを伝えた。<br><br>1ケース（30本）の販売を目的としているため、2缶を重ねて配置することでストック感やボリューム感を演出し、ケース買いという商品特性を視覚的に表現した。<br><br>一部のトマトをイラストに置き換え、写真とイラストを使い分けることで、トマトの豊富さを表現しながら、全体を軽やかにまとめた。",
    time: "5時間",
    size: "1080×1080px",
    tool: "Illustrator / Photoshop",
    value: ["bn"],
    number: 1,
  },
  {
    id: 1003,
    title: "サンドイッチ屋",
    link: "./img/work/flier/sandwich.webp",
    url: "",
    target: "Instagramでお店を探す20〜30代女性",
    purpose: "お店のInstagramを見てもらう",
    point:
      "最終的にInstagramへ目が向くよう、「お店名→商品の魅力→衛生面→Instagram」の順に視線が流れるよう情報を配置し、QRコードの背景に色をつけて目立たせた。<br><br>キッチンカーでの出店販売を行っていることがひと目で伝わるよう、キッチンカーのイラストを配置した。<br><br>人気No.1商品の写真を大きく配置し、サンドイッチの断面や具材のボリューム感を見せることで、食べ応えのある商品の魅力を表現しました。<br><br>「ふんわり」「たっぷり」「満足感」などの言葉を取り入れ、商品の食感やボリュームをイメージしやすくしました。",
    time: "4時間",
    size: "210×297mm",
    tool: "Illustrator / Photoshop / figma",
    value: ["fl"],
    number: 1,
  },
  {
    id: 1004,
    title: "美容液",
    link: "./img/work/banner/skin_serum.webp",
    url: "",
    target: "乾燥に悩む20代〜30代の女性",
    purpose: "美容液に興味を持ってもらい、商品ページへアクセスしてもらう",
    point:
      "「潤い×美白」という商品の特徴が直感的に伝わるように、水しぶきや水面の素材を背景に使用し、みずみずしく潤いのある印象を表現した。<br><br>成分を水滴のような円形の中に配置し、商品の特徴を視覚的に分かりやすく整理しました。<br><br>美白による明るく透明感のある肌をイメージできるよう、モデルの肌や歯の明るさを調整しました。<br><br>モデル・成分・商品を重ねて配置して奥行きと立体感を出し、商品情報に目を向けてもらった後、右下の「詳しくはこちら」へ自然に視線が流れるよう構成しました。",
    time: "4時間",
    size: "1080×1080px",
    tool: "Illustrator / Photoshop",
    value: ["bn"],
    number: 1,
  },
  {
    id: 1005,
    title: "美容室",
    link: "/img/work/flier/hair_salon.webp",
    url: "",
    target: "髪のダメージやパサつきが気になる30代女性",
    purpose: "新規OPENの認知向上と、キャンペーンを通じた新規顧客の獲得",
    point:
      "OPEN記念キャンペーンに帯を付け、髪のダメージやパサつきに悩むターゲットの目に留まりやすいようにキャンペーン情報を強調した。<br><br>髪のサラサラとした質感をイメージできるよう、髪の流れを連想させる曲線的な装飾を取り入れ、やわらかく透明感のある印象を表現した。<br><br>美容室の雰囲気を事前に知ってもらい、安心して来店してもらえるよう、メニューの下に店内写真を配置した。<br><br>チラシを折り曲げて使用する場合も考慮し、メインビジュアルやOPEN情報を上部に、キャンペーンやメニューなどの詳細情報を下部に配置しました。",
    time: "3時間",
    size: "210×297mm",
    tool: "Illustrator / Photoshop",
    value: ["fl"],
    number: 1,
  },
  {
    id: 1006,
    title: "ハンバーガー「BURGER-SHOP RECURRENT」",
    link: "./img/work/web/burger_shop_recurrent.webp",
    url: "https://smwka.github.io/burger-shop-recurrent-site/",
    target: "30代男性",
    purpose: "認知度を上げ、来店してもらう",
    point:
      "HTMLでは内容に適したタグを使用し、CSSではremやpxなど用途に応じて単位を使い分け、HTMLの構造とCSS役割を意識してコーディングした。<br><br>画面幅に応じてレイアウトが切り替わるようにレスポンシブ対応を行、PC、スマートフォンなど異なる画面サイズでも閲覧しやすいようにした。",
    time: "5時間",
    size: "1920p×1080spx",
    tool: "HTML / CSS",
    value: ["web", "cd"],
    number: 1,
  },
  {
    id: 1007,
    title: "夏期講習",
    link: "./img/work/banner/cram_school01.webp",
    url: "",
    target: "真剣に大学受験を目指している高校生",
    purpose: "塾に興味を持ってもらい、公式サイトへアクセスしてもらう",
    point:
      "モデルの視線の先にキャッチコピーを配置し、視線と文字の方向性を揃えることで、受験に向けて前向きに進む印象を表現した。「この夏で見違える学力へ。」の「夏」「見違える」「学力」にジャンプ率をつけ、重要な言葉を強調することで、キャッチコピーに目が留まりやすいようにした。「無料体験実施中」は黄色の背景で強調し、夏期講習に興味を持った人が次の行動につながりやすいよう、目立つ位置に配置しました。「この夏で見違える学力へ。」から「夏期講習」、「無料体験実施中」、「詳しくはこちら」へと視線が流れるよう情報を配置し、Webサイトへのアクセスにつながる導線を意識しました。",
    time: "9時間",
    size: "1080×1080px",
    tool: "Illustrator / Photoshop",
    value: ["bn"],
    number: 1,
  },
  {
    id: 1008,
    title: "夏期講習",
    link: "./img/work/banner/cram_school02.webp",
    url: "",
    target: "初めて塾に通うことに不安があり、安心して楽しく学びたい高校生",
    purpose: "塾に興味を持ってもらい、公式サイトへアクセスしてもらう",
    point:
      "夏期講習」の文字に装飾を加え、空やひまわりの写真を使用することで、夏らしく明るく親しみやすい印象を表現した。笑顔の女性を使用することで、楽しく学べる雰囲気を演出し、初めて塾に通う高校生にも安心感を持ってもらえるようにした。「初めてでも安心」「いつでも質問・相談ができる」など、サポート内容を具体的に掲載することで、塾に通うことへの不安を軽減できるよう工夫した。「入会費無料」を目立たせ、気軽に参加できる印象を与えるとともに、下部の「申し込みはこちら」へ自然に視線が流れるよう構成した。",
    time: "11時間",
    size: "1080×1080px",
    tool: "Illustrator / Photoshop",
    value: ["bn"],
    number: 1,
  },
  {
    id: 1009,
    title: "ハンバーガー",
    link: "./img/work/flier/hamburger.webp",
    url: "",
    target: "ボリュームのあるハンバーガーやチーズが好きな20〜30代男性",
    purpose: "ハンバーガーの購買促進",
    point:
      "A1サイズでの掲示を想定し、遠くからでも情報が認識しやすいよう、文字やロゴのサイズ・配置を調整しました。背景に放射状のラインを取り入れ、中央のハンバーガーへ視線が集まるようにすることで、商品の存在感を高めた。とろけるチーズの表現を加えることで、チーズを特徴とした商品の魅力が視覚的に伝わるよう工夫した。",
    time: "3時間",
    size: "594×841mm",
    tool: "Illustrator / Photoshop",
    value: ["fl"],
    number: 1,
  },
  {
    id: 1010,
    title: "アイス「guilty-cotton」",
    link: "./img/work/web/guilty-cotton.webp",
    url: "https://smwka.github.io/guilty-cotton-site/",
    target: "SNSでお店を探す20代女性",
    purpose: "認知度向上と主客",
    point:
      "CSS Gridを使用し、grid-columやgrid-rowを指定して各要素の配置を細かく調整することで、複数の画像やコンテンツを組み合わせた複雑なレイアウトを表現した。<br><br>項目の追加・削除した場合にもレイアウトが崩れにくくなるように、要素間の余白はmargin-topを使用して設定することを意識した。",
    time: "3時間",
    size: "1920×1080",
    tool: "Illustrator / Photoshop",
    value: ["web", "cd"],
    number: 1,
  },
  {
    id: 1011,
    title: "長濱美術館「モカそれからの100年」",
    link: "./img/work/movie/museum.webp",
    url: "https://youtube.com/shorts/gquQNM0wYCQ?si=SwPhSjWTttf6bcNF",
    target: "毎日のスマホやPC作業に疲れている30代女性",
    purpose: "作品を見に美術館へ足を運んでもらう",
    point:
      "動画の冒頭にターゲットに向けたキャッチコピーを取り入れ、興味を持ってもらえるよう工夫した。<br><br>視聴者が文字を読みやすいよう、テキストを表示するタイミングや表示時間を調整し、内容をしっかり理解できるテンポを意識した。<br><br>美術館で作品を鑑賞しているような雰囲気を演出するため、背景を暗めにし、作品の写真を横方向にスライドさせて順番に見せる構成にした。",
    time: "6時間",
    size: "1080×1920px",
    tool: "Illustrator / Photoshop",
    value: ["mv"],
    number: 1,
  },
];
